### ISSUE TITLE
./build.sh: line 3: gradle: command not found 

### ISSUE THREAD

**Issue by nmexas** [scottlepp/sql-proxy#4]
I get the following issue. We are currently working with Linux VM.

[root@tvprmflat sql-proxy-master]# ./build.sh 
./build.sh: line 3: gradle: command not found 
java.io.FileNotFoundException: ../libs/*.jar (No such file or directory)

Could you please help!

Thank you in advanced,

**Comment by scottlepp** [comment]
> gradle: command not found

[install gradle](https://gradle.org/install/)
